version: "3.2"
services:
  api_dev:
    build: .
    image: highlanderdantas/api-ts
    ports:
      - "5000:3050"
    links:
      - db_mongo
  db_mongo:
    image: tutum/mongodb
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      - AUTH=no